### ISSUE TITLE
最后一步保存权重失败。。。

### ISSUE THREAD

**Issue by jitask** [Tongjilibo/build_MiniLLM_from_scratch#4]
(cuda) I:\build_MiniLLM_from_scratch\pretrain>python pretrain.py
[INFO] token_size: 0, smp_size: 0
[INFO] trainable params: 218155008 || all params: 218155008 || trainable%: 100.0
[INFO] num decayed parameter tensors: 85, with 218,129,408 parameters
[INFO] num non-decayed parameter tensors: 25, with 25,600 parameters
2024-07-11 09:59:24 - Start Training

2024-07-11 09:59:24 - Start  Epoch: 1/1
2024-07-11 09:59:24 - Finish Epoch: 1/1

2024-07-11 09:59:24 - Finish Training
Traceback (most recent call last):
  File "I:\build_MiniLLM_from_scratch\pretrain\pretrain.py", line 148, in <module>
    model.fit(train_dataloader, steps_per_epoch=None, epochs=args.epochs, callbacks=callbacks)
  File "C:\Users\pinbo\.conda\envs\cuda\Lib\site-packages\torch4keras\trainer\base.py", line 416, in fit
    raise e
  File "C:\Users\pinbo\.conda\envs\cuda\Lib\site-packages\torch4keras\trainer\base.py", line 392, in fit
    return self._fit(train_dataloader, steps_per_epoch, epochs, callbacks, verbose, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pinbo\.conda\envs\cuda\Lib\site-packages\torch4keras\trainer\base.py", line 487, in _fit
    self.callbacks.on_train_end(logs)
  File "C:\Users\pinbo\.conda\envs\cuda\Lib\site-packages\torch4keras\callbacks.py", line 140, in on_train_end
    callback.on_train_end(logs)
  File "C:\Users\pinbo\.conda\envs\cuda\Lib\site-packages\torch4keras\callbacks.py", line 910, in on_train_end
    self.trainer.save_to_checkpoint(self.replace_placeholder(self.save_dir, epoch_suffix='final', step_suffix='final', **logs),
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pinbo\.conda\envs\cuda\Lib\site-packages\torch4keras\callbacks.py", line 901, in replace_placeholder
    filepath = filepath.format(epoch=epoch_suffix, step=step_suffix, **logs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'loss'

**Comment by jitask** [comment]
问题解决，配置文件路径问题：
data_path: "../data/corpus/pretrain_data_bin/wiki/wiki.bin"  # 训练数据所在路径
